### ISSUE TITLE
Get services endpoint doesn't follow pagination

### ISSUE THREAD

**Issue by Bre77** [yaleman/pyaussiebb#16]
It would appear the get services function has a page variable but does actually check and loop for pages > 1. Only checked the Asyncio implementation.

Related: https://github.com/home-assistant/core/issues/65760

**Comment by yaleman** [comment]
Notes about this so far:

* It's possible to use the library as-is to sort this, given `get_services()` takes `page` as an input.
* but there's no mechanism to know if you're supposed to ask for page 2...
* so yes, it's something that'd be handy to fix.

The call in `get_services()` to `https://myaussie-api.aussiebroadband.com.au/services?page=1` returns a big JSON object that looks like this:
```
{
    "data": [  <big dict of services here> ],
    "links": {
        "first": "https://myaussie-api.aussiebroadband.com.au/services?page=1",
        "last": "https://myaussie-api.aussiebroadband.com.au/services?page=1",
        "prev": null,
        "next": null
    },
    "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 1,
        "path": "https://myaussie-api.aussiebroadband.com.au/services",
        "per_page": 10,
        "to": 1,
        "total": 1
    }
}
```

So it should be *relatively* trivial to iterate on this - I just can't test it live. I'll ponder it and get to it once it pops up on my radar - happy to accept PR's in the meantime though!

**Comment by yaleman** [comment]
Asking for assistance over here: https://github.com/home-assistant/core/issues/65760#issuecomment-1030641606
