### ISSUE TITLE
Version mismatches

### ISSUE THREAD

**Issue by fabaff** [yaleman/pyaussiebb#214]
Could you please align the version mentioned at various places?

- `pyproject.toml`: 0.1.2 (https://github.com/yaleman/pyaussiebb/blob/main/pyproject.toml#L3)
- PyPI: 0.1.3 (https://pypi.org/project/pyaussiebb/0.1.3/)
- Latest tag: 0.1.1 (https://github.com/yaleman/pyaussiebb/tree/v0.1.1)

Thanks

**Comment by yaleman** [comment]
Had to bump to 0.1.4 to make everything work again, hope that helps.
